export const SET_SELECTED_GENRE = 'SET_SELECTED_GENRE'

export const SET_SELECTED_GENRE_NAME = 'SET_SELECTED_GENRE_NAME'

export const SET_GENRES = 'SET_GENRES'

export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE'

export const SET_MOVIES = 'SET_MOVIES'