name: E2E testing in chrome with Cypress
on:
  push:
    branches:
    - cypress-test
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E testing on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
        env:  
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - run: npm install
      - name: Npm install and build
        run: npm ci && npm run build
      - name: Start dev server
        run: npm start    
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome  