name: Deploy TMDB App
on:
  push:
    branches:
    - dev
    # - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    # - master
    - dev

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version:  10.x
          
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci
      
      - name: Build 
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
