name: Deploy TMDB App
on:
  push:
    branches:
    - dev
    # - master

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    # - master
    - dev

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: 'true'
        env:  
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Npm install
        run: npm ci
      
      - name: Build 
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
